site_name: "UCS503 : Software Engineering Projet: SCBE (Semi Computer Based Evaluation)"
site_url: https://timepassuser.github.io/ucs503p-202627-SCBE/

plugins:
- search
# - gen-files:
#     scripts:
#     - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: summary.md
- section-index
- git-revision-date-localized
# - git-committers:
#     repository: "tiet-unc512/tiet-unc512.github.io"
- git-authors
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          summary: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # show_object_full_path: true
          show_root_full_path: true
          show_root_heading: true
          show_source: false

theme:
  name: material
  custom_dir: docs/assets/theme-overrides
  features:
    - navigation.footer
    - header.autohide
    - content.tabs.link
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - content.tooltips
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle-outline
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: assets/tiet-logo.svg
  favicon: assets/favicon.png

repo_url: https://github.com/timepassuser/ucs503p-202627-SCBE/
repo_name: ucs503p-202627-SCBE
copyright: "Copyright &copy; 2025 <a href='https://bvraghav.com/'>Raghav B. Venkataramaiyer</a> &lt;<code style='color:inherit; background:transparent'>bv.raghav</code>&gt;
          <br> &copy; 2026 <b>Team Infinix</b>"
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/timepassuser/ucs503p-202627-SCBE/
    name: "Deliverables for UCS503P Project: SCBE"

extra_css:
  - assets/stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
- https://unpkg.com/katex@0/dist/katex.min.js
- javascript/arithmatex.js

markdown_extensions:
  - abbr
  - md_in_html
  - attr_list
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {which: generic}
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          arithmatex: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {which: generic}
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # - mkdocs-click
  - toc:
      toc_depth: 4
  - sane_lists
